"""supplier notes

Revision ID: 09b4227fde57
Revises: a38707a5ac63
Create Date: 2026-07-08 12:38:25.923238

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '09b4227fde57'
down_revision: str | None = 'a38707a5ac63'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'notes')
    # ### end Alembic commands ###
