"""notification severity metadata

Revision ID: 0b0a90483fe8
Revises: bb13e084becc
Create Date: 2026-07-08 13:27:00.795858

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0b0a90483fe8'
down_revision: str | None = 'bb13e084becc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('severity', sa.String(length=10), server_default='info', nullable=False))
    op.add_column('notifications', sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.create_index('ix_notifications_recipient_read', 'notifications', ['recipient_user_id', 'read_at'], unique=False)
    op.create_index('ix_notifications_supplier_read', 'notifications', ['recipient_supplier_id', 'read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_supplier_read', table_name='notifications')
    op.drop_index('ix_notifications_recipient_read', table_name='notifications')
    op.drop_column('notifications', 'metadata_json')
    op.drop_column('notifications', 'severity')
    # ### end Alembic commands ###
