"""must_change_password fields

Revision ID: 92c898fa957b
Revises: b18b3ff0e3d2
Create Date: 2026-07-08 16:11:48.861444

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '92c898fa957b'
down_revision: str | None = 'b18b3ff0e3d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('platform_users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('supplier_users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('supplier_users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenant_users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tenant_users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_users', 'password_changed_at')
    op.drop_column('tenant_users', 'must_change_password')
    op.drop_column('supplier_users', 'password_changed_at')
    op.drop_column('supplier_users', 'must_change_password')
    op.drop_column('platform_users', 'password_changed_at')
    op.drop_column('platform_users', 'must_change_password')
    # ### end Alembic commands ###
