"""dock override is_active

Revision ID: a38707a5ac63
Revises: f2b4c0a81a5c
Create Date: 2026-07-08 12:14:24.296798

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a38707a5ac63'
down_revision: str | None = 'f2b4c0a81a5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dock_overrides', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dock_overrides', 'is_active')
    # ### end Alembic commands ###
