"""roles fields and appointment series

Revision ID: b18b3ff0e3d2
Revises: 4f355445323d
Create Date: 2026-07-08 14:44:37.183482

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b18b3ff0e3d2'
down_revision: str | None = '4f355445323d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_series',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('recurrence_frequency', sa.String(length=10), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_appointment_series_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_appointment_series_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_appointment_series_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_series'))
    )
    op.create_index(op.f('ix_appointment_series_facility_id'), 'appointment_series', ['facility_id'], unique=False)
    op.create_index(op.f('ix_appointment_series_supplier_id'), 'appointment_series', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_appointment_series_tenant_id'), 'appointment_series', ['tenant_id'], unique=False)
    op.add_column('appointments', sa.Column('series_id', sa.Uuid(), nullable=True))
    op.add_column('appointments', sa.Column('occurrence_index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_appointments_series_id'), 'appointments', ['series_id'], unique=False)
    op.create_foreign_key(op.f('fk_appointments_series_id_appointment_series'), 'appointments', 'appointment_series', ['series_id'], ['id'], ondelete='SET NULL')
    op.add_column('roles', sa.Column('display_name', sa.String(length=150), nullable=True))
    op.add_column('roles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'description')
    op.drop_column('roles', 'display_name')
    op.drop_constraint(op.f('fk_appointments_series_id_appointment_series'), 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_series_id'), table_name='appointments')
    op.drop_column('appointments', 'occurrence_index')
    op.drop_column('appointments', 'series_id')
    op.drop_index(op.f('ix_appointment_series_tenant_id'), table_name='appointment_series')
    op.drop_index(op.f('ix_appointment_series_supplier_id'), table_name='appointment_series')
    op.drop_index(op.f('ix_appointment_series_facility_id'), table_name='appointment_series')
    op.drop_table('appointment_series')
    # ### end Alembic commands ###
