"""email logs

Revision ID: b8968a9b0efc
Revises: 0b0a90483fe8
Create Date: 2026-07-08 13:55:35.347568

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b8968a9b0efc'
down_revision: str | None = '0b0a90483fe8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('template_key', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('notification_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_email_logs_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_email_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_logs'))
    )
    op.create_index('ix_email_logs_appointment', 'email_logs', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_email_logs_facility_id'), 'email_logs', ['facility_id'], unique=False)
    op.create_index(op.f('ix_email_logs_tenant_id'), 'email_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_logs_tenant_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_facility_id'), table_name='email_logs')
    op.drop_index('ix_email_logs_appointment', table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
