"""appointment ops fields and index

Revision ID: bb13e084becc
Revises: 09b4227fde57
Create Date: 2026-07-08 13:06:13.321316

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'bb13e084becc'
down_revision: str | None = '09b4227fde57'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('completion_note', sa.Text(), nullable=True))
    op.create_index('ix_appointments_facility_status_start', 'appointments', ['facility_id', 'status', 'scheduled_start_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appointments_facility_status_start', table_name='appointments')
    op.drop_column('appointments', 'completion_note')
    op.drop_column('appointments', 'cancellation_reason')
    # ### end Alembic commands ###
