"""maintenance runs and platform audit permission

Revision ID: ca5e432dfa5e
Revises: aebbb08f3bd8
Create Date: 2026-07-08 18:55:52.377899

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ca5e432dfa5e'
down_revision: str | None = 'aebbb08f3bd8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


platform_roles_table = sa.table(
    "platform_roles",
    sa.column("id", sa.Uuid),
    sa.column("name", sa.String),
    sa.column("permissions_json", sa.JSON),
)


def _sync_platform_role(conn, permissions: list) -> None:
    rows = conn.execute(
        sa.select(platform_roles_table.c.id, platform_roles_table.c.name)
        .where(platform_roles_table.c.name == "Platform Yoneticisi")
    ).all()
    for role_id, _ in rows:
        conn.execute(
            sa.update(platform_roles_table)
            .where(platform_roles_table.c.id == role_id)
            .values(permissions_json=permissions)
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_runs'))
    )
    op.create_index(op.f('ix_maintenance_runs_job_name'), 'maintenance_runs', ['job_name'], unique=False)
    op.create_index('ix_maintenance_runs_job_started', 'maintenance_runs', ['job_name', 'started_at'], unique=False)
    # ### end Alembic commands ###
    # Data-sync: Platform Yoneticisi rolune guncel izin sozlugu (audit.view dahil)
    from app.core.permissions import PlatformPermission

    _sync_platform_role(op.get_bind(), list(PlatformPermission.ALL))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_maintenance_runs_job_started', table_name='maintenance_runs')
    op.drop_index(op.f('ix_maintenance_runs_job_name'), table_name='maintenance_runs')
    op.drop_table('maintenance_runs')
    # ### end Alembic commands ###
    from app.core.permissions import PlatformPermission

    _sync_platform_role(
        op.get_bind(),
        [p for p in PlatformPermission.ALL if p != PlatformPermission.AUDIT_VIEW],
    )
