"""email retry fields and notification preferences

Revision ID: eb8c040a882b
Revises: 92c898fa957b
Create Date: 2026-07-08 17:02:19.751591

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'eb8c040a882b'
down_revision: str | None = '92c898fa957b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('email_logs', sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False))
    op.add_column('email_logs', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('email_logs', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('supplier_users', sa.Column('notification_preferences_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('tenant_users', sa.Column('notification_preferences_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_users', 'notification_preferences_json')
    op.drop_column('supplier_users', 'notification_preferences_json')
    op.drop_column('email_logs', 'last_attempt_at')
    op.drop_column('email_logs', 'next_retry_at')
    op.drop_column('email_logs', 'max_attempts')
    op.drop_column('email_logs', 'retry_count')
    # ### end Alembic commands ###
