"""initial schema

Revision ID: f2b4c0a81a5c
Revises: 
Create Date: 2026-07-08 11:45:32.331391

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f2b4c0a81a5c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.Enum('platform_user', 'tenant_user', 'supplier_user', 'system', name='actortype', native_enum=False, length=32), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('facility_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('before_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('impersonation_session_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_facility_id'), 'audit_logs', ['facility_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('plans',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.Enum('tenant', 'facility', name='planscope', native_enum=False, length=32), nullable=False),
    sa.Column('billing_unit_label', sa.String(length=50), nullable=False),
    sa.Column('measurable_dimensions_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('rate_card_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'retired', name='planstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_plans_name'))
    )
    op.create_table('platform_roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_platform_roles_name'))
    )
    op.create_table('platform_users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='userstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_users'))
    )
    op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
    op.create_table('platform_user_roles',
    sa.Column('platform_user_id', sa.Uuid(), nullable=False),
    sa.Column('platform_role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['platform_role_id'], ['platform_roles.id'], name=op.f('fk_platform_user_roles_platform_role_id_platform_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_user_id'], ['platform_users.id'], name=op.f('fk_platform_user_roles_platform_user_id_platform_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('platform_user_id', 'platform_role_id', name=op.f('pk_platform_user_roles'))
    )
    op.create_table('tenants',
    sa.Column('commercial_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'suspended', 'archived', name='tenantstatus', native_enum=False, length=32), nullable=False),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('billing_contact_name', sa.String(length=255), nullable=True),
    sa.Column('billing_contact_email', sa.String(length=255), nullable=True),
    sa.Column('billing_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('default_language', sa.String(length=10), nullable=False),
    sa.Column('default_timezone', sa.String(length=64), nullable=False),
    sa.Column('assigned_plan_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_plan_id'], ['plans.id'], name=op.f('fk_tenants_assigned_plan_id_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('facilities',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location_metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='facilitystatus', native_enum=False, length=32), nullable=False),
    sa.Column('default_working_profile_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('cargo_default_min_block_minutes', sa.Integer(), nullable=False),
    sa.Column('plan_override_id', sa.Uuid(), nullable=True),
    sa.Column('branding_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_override_id'], ['plans.id'], name=op.f('fk_facilities_plan_override_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_facilities_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_facilities_tenant_id'))
    )
    op.create_index(op.f('ix_facilities_tenant_id'), 'facilities', ['tenant_id'], unique=False)
    op.create_table('dock_conflict_groups',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('relation_type', sa.Enum('mutual_block', 'shared_capacity', 'conditional', name='conflictrelationtype', native_enum=False, length=32), nullable=False),
    sa.Column('trigger_condition_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_dock_conflict_groups_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_dock_conflict_groups_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dock_conflict_groups')),
    sa.UniqueConstraint('facility_id', 'name', name=op.f('uq_dock_conflict_groups_facility_id'))
    )
    op.create_index(op.f('ix_dock_conflict_groups_facility_id'), 'dock_conflict_groups', ['facility_id'], unique=False)
    op.create_index(op.f('ix_dock_conflict_groups_tenant_id'), 'dock_conflict_groups', ['tenant_id'], unique=False)
    op.create_table('docks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('working_hours_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('responsible_user_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_docks_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_docks_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_docks')),
    sa.UniqueConstraint('facility_id', 'name', name=op.f('uq_docks_facility_id'))
    )
    op.create_index(op.f('ix_docks_facility_id'), 'docks', ['facility_id'], unique=False)
    op.create_index(op.f('ix_docks_tenant_id'), 'docks', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_roles_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_roles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('tenant_id', 'facility_id', 'name', name=op.f('uq_roles_tenant_id'))
    )
    op.create_index(op.f('ix_roles_facility_id'), 'roles', ['facility_id'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category_label', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='supplierstatus', native_enum=False, length=32), nullable=False),
    sa.Column('auto_approval_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_block_minutes', sa.Integer(), nullable=True),
    sa.Column('max_block_minutes', sa.Integer(), nullable=True),
    sa.Column('weekly_quota', sa.Integer(), nullable=True),
    sa.Column('monthly_quota', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_suppliers_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_suppliers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('facility_id', 'code', name=op.f('uq_suppliers_facility_id'))
    )
    op.create_index(op.f('ix_suppliers_facility_id'), 'suppliers', ['facility_id'], unique=False)
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_table('tenant_users',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='userstatus', native_enum=False, length=32), nullable=False),
    sa.Column('default_facility_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_facility_id'], ['facilities.id'], name=op.f('fk_tenant_users_default_facility_id_facilities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_users'))
    )
    op.create_index(op.f('ix_tenant_users_email'), 'tenant_users', ['email'], unique=True)
    op.create_index(op.f('ix_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False)
    op.create_table('vehicle_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('physical_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_vehicle_categories_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_vehicle_categories_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_categories')),
    sa.UniqueConstraint('facility_id', 'name', name=op.f('uq_vehicle_categories_facility_id'))
    )
    op.create_index(op.f('ix_vehicle_categories_facility_id'), 'vehicle_categories', ['facility_id'], unique=False)
    op.create_index(op.f('ix_vehicle_categories_tenant_id'), 'vehicle_categories', ['tenant_id'], unique=False)
    op.create_table('dock_conflict_group_members',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('dock_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.id'], name=op.f('fk_dock_conflict_group_members_dock_id_docks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['dock_conflict_groups.id'], name=op.f('fk_dock_conflict_group_members_group_id_dock_conflict_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dock_conflict_group_members')),
    sa.UniqueConstraint('group_id', 'dock_id', name=op.f('uq_dock_conflict_group_members_group_id'))
    )
    op.create_index(op.f('ix_dock_conflict_group_members_dock_id'), 'dock_conflict_group_members', ['dock_id'], unique=False)
    op.create_index(op.f('ix_dock_conflict_group_members_group_id'), 'dock_conflict_group_members', ['group_id'], unique=False)
    op.create_table('dock_overrides',
    sa.Column('dock_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('closed', 'extra_hours', name='dockoverridetype', native_enum=False, length=32), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.id'], name=op.f('fk_dock_overrides_dock_id_docks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_dock_overrides_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_dock_overrides_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dock_overrides'))
    )
    op.create_index(op.f('ix_dock_overrides_date'), 'dock_overrides', ['date'], unique=False)
    op.create_index(op.f('ix_dock_overrides_dock_id'), 'dock_overrides', ['dock_id'], unique=False)
    op.create_index(op.f('ix_dock_overrides_facility_id'), 'dock_overrides', ['facility_id'], unique=False)
    op.create_index(op.f('ix_dock_overrides_tenant_id'), 'dock_overrides', ['tenant_id'], unique=False)
    op.create_table('dock_vehicle_categories',
    sa.Column('dock_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.id'], name=op.f('fk_dock_vehicle_categories_dock_id_docks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_category_id'], ['vehicle_categories.id'], name=op.f('fk_dock_vehicle_categories_vehicle_category_id_vehicle_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dock_id', 'vehicle_category_id', name=op.f('pk_dock_vehicle_categories'))
    )
    op.create_table('facility_memberships',
    sa.Column('tenant_user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_dock_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_facility_memberships_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_facility_memberships_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_user_id'], ['tenant_users.id'], name=op.f('fk_facility_memberships_tenant_user_id_tenant_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_memberships')),
    sa.UniqueConstraint('tenant_user_id', 'facility_id', name=op.f('uq_facility_memberships_tenant_user_id'))
    )
    op.create_index(op.f('ix_facility_memberships_facility_id'), 'facility_memberships', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_memberships_tenant_id'), 'facility_memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_facility_memberships_tenant_user_id'), 'facility_memberships', ['tenant_user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_user_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_supplier_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_notifications_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_supplier_id'], ['suppliers.id'], name=op.f('fk_notifications_recipient_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['tenant_users.id'], name=op.f('fk_notifications_recipient_user_id_tenant_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notifications_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_facility_id'), 'notifications', ['facility_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_supplier_id'), 'notifications', ['recipient_supplier_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_table('product_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_block_minutes', sa.Integer(), nullable=False),
    sa.Column('default_vehicle_category_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['default_vehicle_category_id'], ['vehicle_categories.id'], name=op.f('fk_product_categories_default_vehicle_category_id_vehicle_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_product_categories_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_product_categories_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('facility_id', 'name', name=op.f('uq_product_categories_facility_id'))
    )
    op.create_index(op.f('ix_product_categories_facility_id'), 'product_categories', ['facility_id'], unique=False)
    op.create_index(op.f('ix_product_categories_tenant_id'), 'product_categories', ['tenant_id'], unique=False)
    op.create_table('supplier_users',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='userstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_users_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_users'))
    )
    op.create_index(op.f('ix_supplier_users_email'), 'supplier_users', ['email'], unique=True)
    op.create_index(op.f('ix_supplier_users_supplier_id'), 'supplier_users', ['supplier_id'], unique=False)
    op.create_table('appointments',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('dock_id', sa.Uuid(), nullable=True),
    sa.Column('product_category_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_category_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_unit', sa.Enum('pallet', 'piece', 'box', 'carton', name='quantityunit', native_enum=False, length=32), nullable=False),
    sa.Column('license_plate', sa.String(length=30), nullable=True),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_phone', sa.String(length=50), nullable=True),
    sa.Column('delivery_type', sa.Enum('standard', 'cargo', name='deliverytype', native_enum=False, length=32), nullable=False),
    sa.Column('cargo_window', sa.Enum('morning', 'afternoon', 'all_day', name='cargowindow', native_enum=False, length=32), nullable=True),
    sa.Column('cargo_min_block_minutes', sa.Integer(), nullable=True),
    sa.Column('requested_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'revision_pending', 'rejected', 'completed', 'cancelled', name='appointmentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('revision_note', sa.Text(), nullable=True),
    sa.Column('original_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurring_rule', sa.Enum('weekly', 'biweekly', 'monthly', name='recurringrule', native_enum=False, length=32), nullable=True),
    sa.Column('created_by_type', sa.Enum('supplier', 'tenant_user', 'platform', 'system', name='createdbytype', native_enum=False, length=32), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.id'], name=op.f('fk_appointments_dock_id_docks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_appointments_facility_id_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], name=op.f('fk_appointments_product_category_id_product_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_appointments_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_appointments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_category_id'], ['vehicle_categories.id'], name=op.f('fk_appointments_vehicle_category_id_vehicle_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_dock_id'), 'appointments', ['dock_id'], unique=False)
    op.create_index('ix_appointments_dock_start', 'appointments', ['dock_id', 'scheduled_start_at'], unique=False)
    op.create_index(op.f('ix_appointments_facility_id'), 'appointments', ['facility_id'], unique=False)
    op.create_index('ix_appointments_facility_start', 'appointments', ['facility_id', 'scheduled_start_at'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_supplier_id'), 'appointments', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    op.create_table('dock_product_categories',
    sa.Column('dock_id', sa.Uuid(), nullable=False),
    sa.Column('product_category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dock_id'], ['docks.id'], name=op.f('fk_dock_product_categories_dock_id_docks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], name=op.f('fk_dock_product_categories_product_category_id_product_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dock_id', 'product_category_id', name=op.f('pk_dock_product_categories'))
    )
    op.create_table('facility_membership_roles',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['facility_memberships.id'], name=op.f('fk_facility_membership_roles_membership_id_facility_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_facility_membership_roles_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', 'role_id', name=op.f('pk_facility_membership_roles'))
    )
    op.create_table('supplier_product_categories',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('product_category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], name=op.f('fk_supplier_product_categories_product_category_id_product_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_product_categories_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('supplier_id', 'product_category_id', name=op.f('pk_supplier_product_categories'))
    )
    op.create_table('appointment_revisions',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('old_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_dock_id', sa.Uuid(), nullable=True),
    sa.Column('new_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_dock_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('revised_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_revisions_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_revisions'))
    )
    op.create_index(op.f('ix_appointment_revisions_appointment_id'), 'appointment_revisions', ['appointment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_revisions_appointment_id'), table_name='appointment_revisions')
    op.drop_table('appointment_revisions')
    op.drop_table('supplier_product_categories')
    op.drop_table('facility_membership_roles')
    op.drop_table('dock_product_categories')
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_supplier_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index('ix_appointments_facility_start', table_name='appointments')
    op.drop_index(op.f('ix_appointments_facility_id'), table_name='appointments')
    op.drop_index('ix_appointments_dock_start', table_name='appointments')
    op.drop_index(op.f('ix_appointments_dock_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_supplier_users_supplier_id'), table_name='supplier_users')
    op.drop_index(op.f('ix_supplier_users_email'), table_name='supplier_users')
    op.drop_table('supplier_users')
    op.drop_index(op.f('ix_product_categories_tenant_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_facility_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_supplier_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_facility_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_facility_memberships_tenant_user_id'), table_name='facility_memberships')
    op.drop_index(op.f('ix_facility_memberships_tenant_id'), table_name='facility_memberships')
    op.drop_index(op.f('ix_facility_memberships_facility_id'), table_name='facility_memberships')
    op.drop_table('facility_memberships')
    op.drop_table('dock_vehicle_categories')
    op.drop_index(op.f('ix_dock_overrides_tenant_id'), table_name='dock_overrides')
    op.drop_index(op.f('ix_dock_overrides_facility_id'), table_name='dock_overrides')
    op.drop_index(op.f('ix_dock_overrides_dock_id'), table_name='dock_overrides')
    op.drop_index(op.f('ix_dock_overrides_date'), table_name='dock_overrides')
    op.drop_table('dock_overrides')
    op.drop_index(op.f('ix_dock_conflict_group_members_group_id'), table_name='dock_conflict_group_members')
    op.drop_index(op.f('ix_dock_conflict_group_members_dock_id'), table_name='dock_conflict_group_members')
    op.drop_table('dock_conflict_group_members')
    op.drop_index(op.f('ix_vehicle_categories_tenant_id'), table_name='vehicle_categories')
    op.drop_index(op.f('ix_vehicle_categories_facility_id'), table_name='vehicle_categories')
    op.drop_table('vehicle_categories')
    op.drop_index(op.f('ix_tenant_users_tenant_id'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_email'), table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_facility_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_facility_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_docks_tenant_id'), table_name='docks')
    op.drop_index(op.f('ix_docks_facility_id'), table_name='docks')
    op.drop_table('docks')
    op.drop_index(op.f('ix_dock_conflict_groups_tenant_id'), table_name='dock_conflict_groups')
    op.drop_index(op.f('ix_dock_conflict_groups_facility_id'), table_name='dock_conflict_groups')
    op.drop_table('dock_conflict_groups')
    op.drop_index(op.f('ix_facilities_tenant_id'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_table('tenants')
    op.drop_table('platform_user_roles')
    op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
    op.drop_table('platform_users')
    op.drop_table('platform_roles')
    op.drop_table('plans')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_facility_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
